version: '3.8'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - main
    volumes:
      - "monireh_docker_assignment_1_pg_data:/var/lib/postgresql/data"
      - "../assignment-01/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  query:
    build:
      context: ../assignment-02
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - main
    depends_on:
      - db

volumes:
  monireh_docker_assignment_1_pg_data:

networks:
  main: